### ISSUE TITLE
Trouble In Split View, Brace highlight

### ISSUE THREAD

**Issue by sirius0xff** [Gruntfuggly/scoper#10]
Similar to #2

The brace highlight feature is Great but it has a little bug.

Problem:
Brace highlight won't disappear unless reopening a file/hide the file tab.

How to reproduce:
Open 2 files.
Display each files side by side in split view.
Highlight a scope in one file.
Click the other file then click back.
Highlight in first file stick.

P.S. If you start typing next to the brace, highlight will include the new text.

![2019-11-13_18-48-28](https://user-images.githubusercontent.com/32758498/68757166-6f1efa80-0646-11ea-9b22-0214b9e7a6bf.gif)

**Comment by sirius0xff** [comment]
FYI, new vscode provided a similar feature, but won't work for comments and strings.

**Comment by Gruntfuggly** [comment]
Finally fixed this! Sorry for the the delay... please try the latest version.
