### ISSUE TITLE
scoper highlight takes priority over text select highlight with no option to swap

### ISSUE THREAD

**Issue by the8thbit** [Gruntfuggly/scoper#11]
When a block is selected, if you try to select text within the block, the scoper highlight will cover up your selection.

This can currently be worked around by setting a low opacity for your highlight color.

**Comment by Gruntfuggly** [comment]
You can set the alpha on the scoper highlight to less than 100%. I have mine set to 50%, e.g.
`"scoper.highlightColor": "#00330080"`

**Comment by the8thbit** [comment]
@Gruntfuggly Thanks! This is indeed the work around I'm using. I turned the value and saturation up all the way on the highlight color, then set opacity down to 12%. That's a pretty good simulation of giving selection highlight priority. I figured that out shortly after creating that ticket, and added the edit mentioning that work around, but it would still be nice to be able to do this properly.

Is this a limitation of vscode scripting, or is it just something that hasn't been implemented in this plugin? I haven't worked on vscode extensions at all, but I'd be happy to work on a fix PR at some point, maybe next weekend, or this weekend if I have some time. Just leave this issue open so it shows up in my github, that way I wont forget.

**Comment by Gruntfuggly** [comment]
There isn't really any other option - the extension can't know about any other highlights or selections, so all you can really do is configure the colour with the alpha as best as you can.

**Comment by Gruntfuggly** [comment]
You can set the selection background colour to have a lower alpha too. I've tried experimenting with that, but normally you want the selection highlight to have the highest effect.

To be honest, I've found that the background colouring of the scoper highlight is less useful than the highlighting of the enclosing characters at either end.

![image](https://user-images.githubusercontent.com/376658/81335247-34e76080-909f-11ea-9d87-cdaf7457d258.png)

I have the colour set very low (but enough so it's visible) but the braces are highlighted quite strongly.

**Comment by the8thbit** [comment]
Okie dokie, in that case I'll close the issue!
