### ISSUE TITLE
Unable to highlight text

### ISSUE THREAD

**Issue by kenthinson** [Gruntfuggly/scoper#12]
Hello. If I have scoper installed I can no longer highlight text. Am I missing some setting I need to change or is this a bug?
I can select text and copy it but the highlight color does not actually show.

**Comment by Gruntfuggly** [comment]
Please have a look at this issue: https://github.com/Gruntfuggly/scoper/issues/11
Let me know if doesn't address the problem.

**Comment by kenthinson** [comment]
Thanks that worked
