### ISSUE TITLE
Interferes with text selection

### ISSUE THREAD

**Issue by snaphat** [Gruntfuggly/scoper#13]
When text is selected, this extension over-rides the selection so it isn't shown.

**Comment by Gruntfuggly** [comment]
You can set the alpha in the settings, e.g.
`"scoper.highlightColor": "#ff000080"`

**Comment by snaphat** [comment]
Thanks, that worked! Apologies for the false report.

**Comment by Gruntfuggly** [comment]
No problem 🙂
