### ISSUE TITLE
Trouble In Split View

### ISSUE THREAD

**Issue by sirius0xff** [Gruntfuggly/scoper#2]
**Problem:**
Highlight won't disappear unless reopening a file.

**How to reproduce:**
Open 2 files.
Display each files side by side in split view.
Highlight a scope in one file.
Click the other file then click back.
Highlight in first file stick.

![2018-03-01_13-19-54](https://user-images.githubusercontent.com/32758498/36828202-4a26af8a-1d53-11e8-846c-6d7f1252752a.gif)

It is a great extension and helps a lot in visualizing the active scope.
Thank you very much.

**Comment by Gruntfuggly** [comment]
I see what you mean. I'll look into it.

**Comment by Gruntfuggly** [comment]
Try the latest version.

**Comment by sirius0xff** [comment]
It work's now AFAICT.
Thank you.
