### ISSUE TITLE
Language exclusion (rather than or in addition to inclusion) lists in settings

### ISSUE THREAD

**Issue by KillyMXI** [Gruntfuggly/scoper#5]
I think it will be more practical to have the extension to try do something for all languages and let me disable it for languages I don't like how it work with.

Currently it requires to provide the whole list of languages I'd like it to work with.
Unfortunately, that's not very practical.
I don't know what I will be working with tomorrow. And by then I will just forget to adjust some minor convenience extension...

I want to disable it for F# in this particular case. And while doing so, I want it to be future proof - don't limit me in areas beyond my current concern and don't require me to keep it in mind for adjustments before I really need to.

**Comment by Gruntfuggly** [comment]
How about I add a simple option to invert the language support logic - that way it won't break anybody's existing configuration, but should work for you.

**Comment by KillyMXI** [comment]
If I got it right, your proposal will make it even more confusing than it is now.
I would put more thought into designing new configuration parameters and marked existing ones as deprecated.

Options are plenty, and since there is no obvious way to make it work with new settings editor, we are free to do anything that can be edited in settings.json directly.

### First proposal (simpler)

Simplest thing to do (not exactly prettiest) is to keep existing logic but with more clear names and split into inclusion and exclusion lists.
```
"scoper.languages.braces.include": [],
"scoper.languages.braces.exclude": [],
"scoper.languages.parentheses.include": [],
"scoper.languages.parentheses.exclude": [],
"scoper.languages.squareBrackets.include": [],
"scoper.languages.squareBrackets.exclude": [],
```
Keep old parameters synonymous to ".include" but mark as deprecated.
The check logic will be as following: "if (inclusion list is not defined or it contains the language) and (exclusion list is not defined or it does not contain the language)".

### Second proposal (hopefully better)

The prettier way in my opinion will be to mimic the practice of language overrides:
```
"scoper.defaults.braces": true,
"scoper.defaults.parentheses": true,
"scoper.defaults.squareBrackets": true,
"scoper.languages": {
    "[fsharp]": {
        "braces": false,
        "parentheses": false,
        "squareBrackets": false,
    }
}
```
This way the defaults can be set in the new settings editor and per-language overrides can be set in settings.json.
I hope vscode can autocomplete languages in extension parameters this way.
The code to keep the legacy parameters working will be less pretty, but should still be possible to do.

*I don't know if you have any stats about how many people are using the existing parameters to set the languages lists. But even if I were unable to pull the compatibility with the old parameters, the benefits of change will overweight the possible losses for this particular extension. I would do it anyway but put a big explanation note in the changelog and readme.
The worst could happen is people will get highlights where they disabled them (intentionally or not) - only visual thing, no change in behaviour. And it will require to update extension settings once.*

**Comment by Gruntfuggly** [comment]
What's funny is that your second proposal is very similar to how it used to work - using language how vscode does, e.g.:
```
    "[jsonc]": {
        "scoper.squareBrackets": false
    },
```
The problem was that the settings get incorrectly highlighted as problems.

However your proposal will be better as it will be hidden from vscode's view...

I think it will be possible to allow the extension to interpret the settings in both ways. I don't think the settings GUI will allow the languages to autocomplete, but it will definitely by nicer for the default users.

 I'll try and update it this weekend.

**Comment by KillyMXI** [comment]
Relevant issue: https://github.com/Microsoft/vscode/issues/26707

**Comment by Gruntfuggly** [comment]
Latest version now supports your second proposal. Existing users settings should get automatically migrated. 

Note that the language selection does not need the square brackets.

**Comment by KillyMXI** [comment]
Thank you. It works now.
Just a little typo in the changelog...

**Comment by Gruntfuggly** [comment]
Sorry - I'll fix it with the next release. Should have copy and pasted it! :smile:
