### ISSUE TITLE
Highlight is left behind when cursor moved to non-enclosed location

### ISSUE THREAD

**Issue by KillyMXI** [Gruntfuggly/scoper#6]
Consider following code:
```javascript
export const VALUES = [1,2,3,4 /*enclosed*/ ];
/* non-enclosed */
```
1. put cursor inside brackets - brackets highlighted;
2. put cursor to non-enclosed comment - brackets still highlighted.

I find it very annoying and consider it a bug.
Highlighting should be cleared.

If this is not a bug then it should be configurable.

**Comment by Gruntfuggly** [comment]
Please try the latest version - it should now remove the highlight when nothing is matched.

**Comment by KillyMXI** [comment]
Thank you. It works nicely now.
