### ISSUE TITLE
Scoper hide builtin selection highlighting in recent version

### ISSUE THREAD

**Issue by sirius0xff** [Gruntfuggly/scoper#8]
vscode version: 1.37.1
scoper version: 0.0.10

### example:
cursor selected "abcd" in first line, but cannot see the selection highlighting

![image](https://user-images.githubusercontent.com/32758498/63662502-42023f00-c7f1-11e9-9ca4-cfec72deda2b.png)

All other highlighting work, as far as I can tell.

**Comment by Gruntfuggly** [comment]
You can set the scoper highlight alpha channel in order to see the other highlighting. E.g.

`"scoper.highlightColor" : "#ff000080"`

will give you a 50% red highlight.
