### ISSUE TITLE
Visual Studio extension

### ISSUE THREAD

**Issue by BOBJohnson** [Gruntfuggly/scoper#9]
Would it be possible for you to add Visual Studio support for this extension as well?

**Comment by Gruntfuggly** [comment]
Unfortunately extensions for Visual Studio are written completely differently. VSCode is very easy to write extensions for because it runs node/javascript. I wouldn't know where to start converting it for Visual Studio. Sorry.

**Comment by BOBJohnson** [comment]
Ah. Thanks for letting me know.
